name: learn_dart
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: Puneet <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  sqljocky5: any
#  http: "^0.11.3+16"
#  path: ^1.4.1
#  feedparser: ^0.0.2
#  webfeed: ^0.2.1
#  archive: any
#  pointycastle: ^0.11.1

dev_dependencies:
  test: ^0.12.0
